### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by 89z** [Velocidex/go-pe#17]
Other packages can extract PE overlay:

- https://godoc.org/github.com/mewrev/pe#File.Overlay
- https://pkg.go.dev/github.com/fcharlie/buna@master/debug/pe#File.Overlay
- https://github.com/erocarrera/pefile

**Comment by scudette** [comment]
It should be trivial to figure out where the last section is and read to the end of the file. The overlay is not strictly part of the PE file though (e.g. is it not included in Authenticode signatures).
