### ISSUE TITLE
How to get signer certificate SHA-1 fingerprint?

### ISSUE THREAD

**Issue by fhcat** [Velocidex/go-pe#24]
I would like to use the functions in authenticode.go to get the signer's certificate SHA-1 fingerprint. I think currently it is outputting the certificate serial number. But I need to get the SHA-1 fingerprint. aka` thumbprint`.  Any way I can get that?

**Comment by scudette** [comment]
This suggests it is just the hash over the DER encoded certificate
https://stackoverflow.com/questions/4803799/how-to-calculate-x-509-certificates-sha-1-fingerprint

**Comment by fhcat** [comment]
We would like to implement that for use in our project. We can fork your repo. Would you mind us creating a PR once we implement that?

**Comment by scudette** [comment]
Absolutely - love to have a PR :-).

**Comment by fhcat** [comment]
Thanks! Will work on it.
