### ISSUE TITLE
Unexpected Value for TimeDateStamp

### ISSUE THREAD

**Issue by tankbusta** [Velocidex/go-pe#8]
Starting with Windows 10, `TimeDateStamp` no longer indicates the date and time when a PE file was compiled (See https://devblogs.microsoft.com/oldnewthing/20180103-00/?p=97705). This was changed to allow for reproducible builds. 

Would you consider moving this from the formatted string to the raw value?

**Comment by scudette** [comment]
We could change it to a time.Time type which is more consistent with a timestamp anyway.

**Comment by tankbusta** [comment]
While `time.Time` would be more appropriate it's **not** a timestamp anymore (it's some deterministic compile/build hash) in Windows 10 and will lead to unexpected results.

If anything maybe adding something like `TimeDateStamp` and `TimeDateStamp_Raw` would be better?

**Comment by scudette** [comment]
We now export the raw timestamp as well
